-- Initialize roles
INSERT INTO roles (id, name) VALUES (1, 'ROLE_ADMIN') ON CONFLICT (id) DO NOTHING;
INSERT INTO roles (id, name) VALUES (2, 'ROLE_PHARMACIST') ON CONFLICT (id) DO NOTHING;
INSERT INTO roles (id, name) VALUES (3, 'ROLE_SALESPERSON') ON CONFLICT (id) DO NOTHING;
INSERT INTO roles (id, name) VALUES (4, 'ROLE_MANAGER') ON CONFLICT (id) DO NOTHING;
